### ISSUE TITLE
Implemnetations of Component InfoModal 

### ISSUE THREAD

**Issue by JoseMurilloc** [JoseMurilloc/flex-app-diet#1]
## To-do list

- [x] Add space in screen of modal the info food 
- [x] Click in button of "cancelar" must close the modal
- [x] Click in button "adicionar" must add food in dish in context the meal
- [x] Formatted number calories total for only two decimal places
- [x] Each child in a list should have a unique "key" prop in component picker
- [x] Verify what user not  submit food without numberServing
